#Rooms are in TOML Format.
#[Character]
#Directions (Dict of true or false)
#Objects (In a list, with IDs.)
#Image (If Applicable.)
#Color (Color that the tile will be when looked at on the map. [R,G,B])


[1]
Directions = { N = true, E = true, S = true, W = true }
Objects = []
Image = 'images/Gradient.png'
Colour = [255,255,255]

[2]
Directions = { N = true, E = true, S = false, W = true }
Objects = []
Image = 'images/Colors.png'
Colour = [255,0,255]
